
Insert into [Choices] ([QuestionID],[Choices]) 
Values (102,'Angular')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (102,'React.js')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (102,'Vue.js')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (103,'Angular')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (103,'Django')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (103,'Laravel')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (104,'Facebook')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (104,'Google')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (104,'Microsoft')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (105,'Back-end development')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (105,'Server-side rendering')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (105,' Front-end user interfaces')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (106,'8')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (106,'10')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (106,'12')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (107,'Sass')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (107,'Less')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (107,'Stylus')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (108,'Server-side scripting')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (108,'Front-end styling')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (108,'Database management')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (109,'Two-way data binding')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (109,'Virtual DOM')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (109,' Server-side rendering only')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (110,'Single Page Application')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (110,'Server-Provided Architecture')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (110,'Structured Programming Approach')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (111,'Twitter')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (111,'Facebook')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (111,'Google')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (112,'A Progressive Framework')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (112,'The Modern Framework')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (112,'The Angular Alternative')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (113,'TRUE')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (113,'FALSE')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (114,'TRUE')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (114,'FALSE')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (115,'TRUE')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (115,'FALSE')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (116,'TRUE')
Insert into [Choices] ([QuestionID],[Choices]) 
Values (116,'FALSE')