Insert into [Questions] ([QuestionID],[CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','Which of the following frameworks is known for its simplicity and ease of integration, often referred to as "The Progressive JavaScript Framework"?','Vue.js')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','Which of the following is a JavaScript framework for building user interfaces?','Angular')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','React.js is primarily developed and maintained by which company?','Facebook')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','What does Vue.js focus on?','Front-end user interfaces')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','How many columns is Bootstraps grid system based on?','12')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','Which CSS preprocessor is commonly used with Front-End Frameworks?',' Sass')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','What is the primary purpose of Bulma?','Front-end styling')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','Which of the following is a feature of React.js?','Virtual DOM')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','What does the term "SPA" stand for in the context of Front-End Frameworks?','Single Page Application')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','Which company developed and maintains the Bootstrap framework?','Twitter')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'MCQ','What is the tagline of Vue.js?','A Progressive Framework')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'TF','React.js uses a virtual DOM for efficient updates to the user interface','True')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'TF','Bootstrap is primarily a JavaScript framework for building dynamic web applications.',' False')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'TF','Vue.js allows for two-way data binding, similar to Angular.','True')
Insert into [Questions] ([CourseID],[QuestionType],[QuestionTitle],[CorrectAnswer]) 
Values (25,'TF','VFlexbox is a layout model commonly used in the Bootstrap framework.',' False')


